# 指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js: stable

# 设置缓存文件
cache:
  directories:
    - node_modules


# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - sourcode



#在构建之前安装hexo环境
before_install:
  - npm install -g hexo-cli

#安装git插件和搜索功能插件
install:
  - npm install
  - npm install hexo-deployer-git --save
  
# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate


# 设置git提交名，邮箱；替换真实token到_config.yml文件
before_script:
  - git config user.name "yimin417"
  - git config user.email "1414876235@qq.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  - sed -i "s/access_token/${ACCESS_TOKEN}/g"./_config.yml
  - hexo deploy


# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
# notifications:
  # email:
    # - 1414876235@qq.com
  # on_success: change
  # on_failure: always